/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SustainabilityResponsibleSourcingRouteImport } from './routes/sustainability.responsible-sourcing'
import { Route as SustainabilityCommunityImpactRouteImport } from './routes/sustainability.community-impact'
import { Route as SustainabilityClimateActionRouteImport } from './routes/sustainability.climate-action'
import { Route as SustainabilityCircularPackagingRouteImport } from './routes/sustainability.circular-packaging'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as NewsMediaResourcesRouteImport } from './routes/news.media-resources'
import { Route as NewsLatestNewsRouteImport } from './routes/news.latest-news'
import { Route as NewsInnovationRouteImport } from './routes/news.innovation'
import { Route as NewsCompanyStoriesRouteImport } from './routes/news.company-stories'
import { Route as AboutStoryRouteImport } from './routes/about.story'
import { Route as AboutPurposeRouteImport } from './routes/about.purpose'
import { Route as AboutLeadershipRouteImport } from './routes/about.leadership'
import { Route as AboutGlobalPresenceRouteImport } from './routes/about.global-presence'
import { Route as ProductsCategorySlugRouteImport } from './routes/products.category.$slug'
import { Route as ProductsCategoryCategoryRouteImport } from './routes/products.category.$category'
import { Route as ProductsBrandSlugRouteImport } from './routes/products.brand.$slug'

const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityResponsibleSourcingRoute =
  SustainabilityResponsibleSourcingRouteImport.update({
    id: '/responsible-sourcing',
    path: '/responsible-sourcing',
    getParentRoute: () => SustainabilityRoute,
  } as any)
const SustainabilityCommunityImpactRoute =
  SustainabilityCommunityImpactRouteImport.update({
    id: '/community-impact',
    path: '/community-impact',
    getParentRoute: () => SustainabilityRoute,
  } as any)
const SustainabilityClimateActionRoute =
  SustainabilityClimateActionRouteImport.update({
    id: '/climate-action',
    path: '/climate-action',
    getParentRoute: () => SustainabilityRoute,
  } as any)
const SustainabilityCircularPackagingRoute =
  SustainabilityCircularPackagingRouteImport.update({
    id: '/circular-packaging',
    path: '/circular-packaging',
    getParentRoute: () => SustainabilityRoute,
  } as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsMediaResourcesRoute = NewsMediaResourcesRouteImport.update({
  id: '/media-resources',
  path: '/media-resources',
  getParentRoute: () => NewsRoute,
} as any)
const NewsLatestNewsRoute = NewsLatestNewsRouteImport.update({
  id: '/latest-news',
  path: '/latest-news',
  getParentRoute: () => NewsRoute,
} as any)
const NewsInnovationRoute = NewsInnovationRouteImport.update({
  id: '/innovation',
  path: '/innovation',
  getParentRoute: () => NewsRoute,
} as any)
const NewsCompanyStoriesRoute = NewsCompanyStoriesRouteImport.update({
  id: '/company-stories',
  path: '/company-stories',
  getParentRoute: () => NewsRoute,
} as any)
const AboutStoryRoute = AboutStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => AboutRoute,
} as any)
const AboutPurposeRoute = AboutPurposeRouteImport.update({
  id: '/purpose',
  path: '/purpose',
  getParentRoute: () => AboutRoute,
} as any)
const AboutLeadershipRoute = AboutLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => AboutRoute,
} as any)
const AboutGlobalPresenceRoute = AboutGlobalPresenceRouteImport.update({
  id: '/global-presence',
  path: '/global-presence',
  getParentRoute: () => AboutRoute,
} as any)
const ProductsCategorySlugRoute = ProductsCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsCategoryCategoryRoute =
  ProductsCategoryCategoryRouteImport.update({
    id: '/category/$category',
    path: '/category/$category',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsBrandSlugRoute = ProductsBrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustainability': typeof SustainabilityRouteWithChildren
  '/about/global-presence': typeof AboutGlobalPresenceRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/purpose': typeof AboutPurposeRoute
  '/about/story': typeof AboutStoryRoute
  '/news/company-stories': typeof NewsCompanyStoriesRoute
  '/news/innovation': typeof NewsInnovationRoute
  '/news/latest-news': typeof NewsLatestNewsRoute
  '/news/media-resources': typeof NewsMediaResourcesRoute
  '/product/$slug': typeof ProductSlugRoute
  '/sustainability/circular-packaging': typeof SustainabilityCircularPackagingRoute
  '/sustainability/climate-action': typeof SustainabilityClimateActionRoute
  '/sustainability/community-impact': typeof SustainabilityCommunityImpactRoute
  '/sustainability/responsible-sourcing': typeof SustainabilityResponsibleSourcingRoute
  '/products/brand/$slug': typeof ProductsBrandSlugRoute
  '/products/category/$category': typeof ProductsCategoryCategoryRoute
  '/products/category/$slug': typeof ProductsCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustainability': typeof SustainabilityRouteWithChildren
  '/about/global-presence': typeof AboutGlobalPresenceRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/purpose': typeof AboutPurposeRoute
  '/about/story': typeof AboutStoryRoute
  '/news/company-stories': typeof NewsCompanyStoriesRoute
  '/news/innovation': typeof NewsInnovationRoute
  '/news/latest-news': typeof NewsLatestNewsRoute
  '/news/media-resources': typeof NewsMediaResourcesRoute
  '/product/$slug': typeof ProductSlugRoute
  '/sustainability/circular-packaging': typeof SustainabilityCircularPackagingRoute
  '/sustainability/climate-action': typeof SustainabilityClimateActionRoute
  '/sustainability/community-impact': typeof SustainabilityCommunityImpactRoute
  '/sustainability/responsible-sourcing': typeof SustainabilityResponsibleSourcingRoute
  '/products/brand/$slug': typeof ProductsBrandSlugRoute
  '/products/category/$category': typeof ProductsCategoryCategoryRoute
  '/products/category/$slug': typeof ProductsCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustainability': typeof SustainabilityRouteWithChildren
  '/about/global-presence': typeof AboutGlobalPresenceRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/purpose': typeof AboutPurposeRoute
  '/about/story': typeof AboutStoryRoute
  '/news/company-stories': typeof NewsCompanyStoriesRoute
  '/news/innovation': typeof NewsInnovationRoute
  '/news/latest-news': typeof NewsLatestNewsRoute
  '/news/media-resources': typeof NewsMediaResourcesRoute
  '/product/$slug': typeof ProductSlugRoute
  '/sustainability/circular-packaging': typeof SustainabilityCircularPackagingRoute
  '/sustainability/climate-action': typeof SustainabilityClimateActionRoute
  '/sustainability/community-impact': typeof SustainabilityCommunityImpactRoute
  '/sustainability/responsible-sourcing': typeof SustainabilityResponsibleSourcingRoute
  '/products/brand/$slug': typeof ProductsBrandSlugRoute
  '/products/category/$category': typeof ProductsCategoryCategoryRoute
  '/products/category/$slug': typeof ProductsCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/news'
    | '/products'
    | '/search'
    | '/sitemap.xml'
    | '/sustainability'
    | '/about/global-presence'
    | '/about/leadership'
    | '/about/purpose'
    | '/about/story'
    | '/news/company-stories'
    | '/news/innovation'
    | '/news/latest-news'
    | '/news/media-resources'
    | '/product/$slug'
    | '/sustainability/circular-packaging'
    | '/sustainability/climate-action'
    | '/sustainability/community-impact'
    | '/sustainability/responsible-sourcing'
    | '/products/brand/$slug'
    | '/products/category/$category'
    | '/products/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/news'
    | '/products'
    | '/search'
    | '/sitemap.xml'
    | '/sustainability'
    | '/about/global-presence'
    | '/about/leadership'
    | '/about/purpose'
    | '/about/story'
    | '/news/company-stories'
    | '/news/innovation'
    | '/news/latest-news'
    | '/news/media-resources'
    | '/product/$slug'
    | '/sustainability/circular-packaging'
    | '/sustainability/climate-action'
    | '/sustainability/community-impact'
    | '/sustainability/responsible-sourcing'
    | '/products/brand/$slug'
    | '/products/category/$category'
    | '/products/category/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/news'
    | '/products'
    | '/search'
    | '/sitemap.xml'
    | '/sustainability'
    | '/about/global-presence'
    | '/about/leadership'
    | '/about/purpose'
    | '/about/story'
    | '/news/company-stories'
    | '/news/innovation'
    | '/news/latest-news'
    | '/news/media-resources'
    | '/product/$slug'
    | '/sustainability/circular-packaging'
    | '/sustainability/climate-action'
    | '/sustainability/community-impact'
    | '/sustainability/responsible-sourcing'
    | '/products/brand/$slug'
    | '/products/category/$category'
    | '/products/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  NewsRoute: typeof NewsRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SustainabilityRoute: typeof SustainabilityRouteWithChildren
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability/responsible-sourcing': {
      id: '/sustainability/responsible-sourcing'
      path: '/responsible-sourcing'
      fullPath: '/sustainability/responsible-sourcing'
      preLoaderRoute: typeof SustainabilityResponsibleSourcingRouteImport
      parentRoute: typeof SustainabilityRoute
    }
    '/sustainability/community-impact': {
      id: '/sustainability/community-impact'
      path: '/community-impact'
      fullPath: '/sustainability/community-impact'
      preLoaderRoute: typeof SustainabilityCommunityImpactRouteImport
      parentRoute: typeof SustainabilityRoute
    }
    '/sustainability/climate-action': {
      id: '/sustainability/climate-action'
      path: '/climate-action'
      fullPath: '/sustainability/climate-action'
      preLoaderRoute: typeof SustainabilityClimateActionRouteImport
      parentRoute: typeof SustainabilityRoute
    }
    '/sustainability/circular-packaging': {
      id: '/sustainability/circular-packaging'
      path: '/circular-packaging'
      fullPath: '/sustainability/circular-packaging'
      preLoaderRoute: typeof SustainabilityCircularPackagingRouteImport
      parentRoute: typeof SustainabilityRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/media-resources': {
      id: '/news/media-resources'
      path: '/media-resources'
      fullPath: '/news/media-resources'
      preLoaderRoute: typeof NewsMediaResourcesRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/latest-news': {
      id: '/news/latest-news'
      path: '/latest-news'
      fullPath: '/news/latest-news'
      preLoaderRoute: typeof NewsLatestNewsRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/innovation': {
      id: '/news/innovation'
      path: '/innovation'
      fullPath: '/news/innovation'
      preLoaderRoute: typeof NewsInnovationRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/company-stories': {
      id: '/news/company-stories'
      path: '/company-stories'
      fullPath: '/news/company-stories'
      preLoaderRoute: typeof NewsCompanyStoriesRouteImport
      parentRoute: typeof NewsRoute
    }
    '/about/story': {
      id: '/about/story'
      path: '/story'
      fullPath: '/about/story'
      preLoaderRoute: typeof AboutStoryRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/purpose': {
      id: '/about/purpose'
      path: '/purpose'
      fullPath: '/about/purpose'
      preLoaderRoute: typeof AboutPurposeRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/leadership': {
      id: '/about/leadership'
      path: '/leadership'
      fullPath: '/about/leadership'
      preLoaderRoute: typeof AboutLeadershipRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/global-presence': {
      id: '/about/global-presence'
      path: '/global-presence'
      fullPath: '/about/global-presence'
      preLoaderRoute: typeof AboutGlobalPresenceRouteImport
      parentRoute: typeof AboutRoute
    }
    '/products/category/$slug': {
      id: '/products/category/$slug'
      path: '/category/$slug'
      fullPath: '/products/category/$slug'
      preLoaderRoute: typeof ProductsCategorySlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/category/$category': {
      id: '/products/category/$category'
      path: '/category/$category'
      fullPath: '/products/category/$category'
      preLoaderRoute: typeof ProductsCategoryCategoryRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/brand/$slug': {
      id: '/products/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/products/brand/$slug'
      preLoaderRoute: typeof ProductsBrandSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface AboutRouteChildren {
  AboutGlobalPresenceRoute: typeof AboutGlobalPresenceRoute
  AboutLeadershipRoute: typeof AboutLeadershipRoute
  AboutPurposeRoute: typeof AboutPurposeRoute
  AboutStoryRoute: typeof AboutStoryRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutGlobalPresenceRoute: AboutGlobalPresenceRoute,
  AboutLeadershipRoute: AboutLeadershipRoute,
  AboutPurposeRoute: AboutPurposeRoute,
  AboutStoryRoute: AboutStoryRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface NewsRouteChildren {
  NewsCompanyStoriesRoute: typeof NewsCompanyStoriesRoute
  NewsInnovationRoute: typeof NewsInnovationRoute
  NewsLatestNewsRoute: typeof NewsLatestNewsRoute
  NewsMediaResourcesRoute: typeof NewsMediaResourcesRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsCompanyStoriesRoute: NewsCompanyStoriesRoute,
  NewsInnovationRoute: NewsInnovationRoute,
  NewsLatestNewsRoute: NewsLatestNewsRoute,
  NewsMediaResourcesRoute: NewsMediaResourcesRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ProductsRouteChildren {
  ProductsBrandSlugRoute: typeof ProductsBrandSlugRoute
  ProductsCategoryCategoryRoute: typeof ProductsCategoryCategoryRoute
  ProductsCategorySlugRoute: typeof ProductsCategorySlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsBrandSlugRoute: ProductsBrandSlugRoute,
  ProductsCategoryCategoryRoute: ProductsCategoryCategoryRoute,
  ProductsCategorySlugRoute: ProductsCategorySlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface SustainabilityRouteChildren {
  SustainabilityCircularPackagingRoute: typeof SustainabilityCircularPackagingRoute
  SustainabilityClimateActionRoute: typeof SustainabilityClimateActionRoute
  SustainabilityCommunityImpactRoute: typeof SustainabilityCommunityImpactRoute
  SustainabilityResponsibleSourcingRoute: typeof SustainabilityResponsibleSourcingRoute
}

const SustainabilityRouteChildren: SustainabilityRouteChildren = {
  SustainabilityCircularPackagingRoute: SustainabilityCircularPackagingRoute,
  SustainabilityClimateActionRoute: SustainabilityClimateActionRoute,
  SustainabilityCommunityImpactRoute: SustainabilityCommunityImpactRoute,
  SustainabilityResponsibleSourcingRoute:
    SustainabilityResponsibleSourcingRoute,
}

const SustainabilityRouteWithChildren = SustainabilityRoute._addFileChildren(
  SustainabilityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  NewsRoute: NewsRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SustainabilityRoute: SustainabilityRouteWithChildren,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
